### ISSUE TITLE
Templates no longer render after update to 1.4.0

### ISSUE THREAD

**Issue by kaechele** [thomasloven/lovelace-template-entity-row#120]
Somehow templates stopped rendering in my card after updating to 1.4.0 today. Everything works fine after a downgrade to 1.3.2.
- HA version is 2024.2.1
- Installed via HACS

Here's what it should look like:
![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/454490/34b0e429-b7e9-469b-9b7d-f7e664aa0fde)

This is what it looks like with 1.4.0:
![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/454490/ed4ecb90-04d1-435c-b2d7-8cc1526124a0)

Card YAML
```yaml
type: entities
show_header_toggle: false
title: At a Glance
entities:
  - type: custom:template-entity-row
    entity: sensor.recollect_waste
    name: >
      Waste Pickup:  {% for item in
      state_attr('sensor.recollect_waste','pickup_types') -%}

      {%- if loop.first == false %}, {% endif -%}

      {{ item |  replace("recycling_Cart","Recycling") |
      replace("Organics_Cart","Organics") | replace("Garbage_Cart","Garbage") |
      replace("TextileCollectionWeek","Textiles") |
      replace("ElectronicsCollectionWeek", "Electronics") | title }}

      {%- endfor -%}
    icon: |
      {%- set items = state_attr('sensor.recollect_waste','pickup_types') -%}
      {%- if 'recycling_Cart' in items -%}mdi:newspaper
      {%- else -%}mdi:trash-can-outline
      {%- endif -%}
    active: |
      {%- set next = as_timestamp(states('sensor.recollect_waste')) -%}
      {%- set days = (next - as_timestamp(now())) / 86400 -%}
      {{ 0 < days < 1 }}
    state: |
      {%- set next = as_timestamp(states('sensor.recollect_waste')) -%}
      {%- set days = (next - as_timestamp(now())) / 86400 -%}
      {%- if days < 1.0 and days > 0 -%}Tomorrow
      {%- elif days < 0 and days > -1 -%}Today
      {%- elif days < -1 and days > -2 -%}Yesterday
      {%- elif days < -2 -%}{{ days | abs | round(0,'ceil') }} days ago
      {%- else -%}{{ days | round(0,'ceil') }} days
      {%- endif -%}
    secondary: >
      {%- set next = as_timestamp(states('sensor.recollect_waste')) -%} {%- if
      next | timestamp_custom('%a',false) != 'Thu' -%}⚠️ {% endif -%} {{ next |
      timestamp_custom('%A, %B %-d',false) }}
  - entity: >-
      sensor.alectra_utilities_corporation_powerstream_rate_zone_residential_rate
    type: custom:template-entity-row
    name: Electricity Rate
    state: >-
      {{
      states('sensor.alectra_utilities_corporation_powerstream_rate_zone_residential_rate')
      }} $/kWh
    secondary: >
      {%- set active_peak =
      state_attr('sensor.alectra_utilities_corporation_powerstream_rate_zone_residential_rate',
      'active_peak') -%} {%- if active_peak == 'on_peak' -%}On Peak {%- elif
      active_peak == 'mid_peak' -%}Mid Peak {%- else -%}Off Peak {%- endif -%}
    color: >
      {%- set active_peak =
      state_attr('sensor.alectra_utilities_corporation_powerstream_rate_zone_residential_rate',
      'active_peak') -%} {%- if active_peak == 'on_peak' -%}red {%- elif
      active_peak == 'mid_peak' -%}yellow {%- else -%}green {%- endif -%}
  - entity: sensor.airthings_living_room_co2
    name: CO₂
  - entity: sensor.airthings_living_room_radon
    name: Radon
    icon: mdi:radioactive
```

**Comment by jasonc-glitch** [comment]
I'm having the same issue running version 1.4 with Home Assistant 2024.2.1.

Have uninstalled the add on and reinstalled, multiple restarts and the problem remains.

**Comment by Mariusthvdb** [comment]
can comfirm all secondary templates to no longer work if the config.entity is called, all report None or undefined.in the logger

```
Logger: homeassistant.helpers.event
Source: helpers/template.py:574
First occurred: 08:43:02 (20 occurrences)
Last logged: 09:00:17

Error while processing template: Template<template=({% if states[config.entity] is not none %} {% set id = state_attr(config.entity,'friename').split('hygro')[0] %} {{id}} {% else %} Initialiseren {% endif %}) renders=6>
Error while processing template: Template<template=({% if states[config.entity] is not none %} {% set id = state_attr(config.entity,'friname').split('hygro')[0] %} {{id}} {% else %} Initialiseren {% endif %}) renders=6>
Error while processing template: Template<template=({% if states[config.entity] is not none %} {% set id = state_attr(config.entity,'frname').split('hygro')[0] %} {{id}} {% else %} Initialiseren {% endif %}) renders=6>
Error while processing template: Template<template=({% if states[config.entity] is not none %} {% set id = state_attr(config.entity,'fname').split('hygro')[0] %} {{id}} {% else %} Initialiseren {% endif %}) renders=6>
Error while processing template: Template<template=({% if states[config.entity] is not none %} {% set id = state_attr(config.entity,'name').split('hygro')[0] %} {{id}} {% else %} Initialiseren {% endif %}) renders=6>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 572, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2332, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 7, in top-level template code
jinja2.exceptions.UndefinedError: 'id' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 698, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 574, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'id' is undefined
```

**Comment by thomasloven** [comment]
I was not able to reproduce this, but I've tried to fix the only related thing that was changed in 1.4.0.

**Comment by Mariusthvdb** [comment]
can confirm the template to show correctly again, thx

<img width="553" alt="Scherm­afbeelding 2024-02-12 om 11 47 45" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/44bf57c4-4c1f-460d-957c-b3b109d94c4b">

**Comment by jasonc-glitch** [comment]
Also fixed it for me.   Thank you!

**Comment by kaechele** [comment]
1.4.1 works. Thanks!
